name: contour # you probably want to 'snapcraft register <name>'

#XXX version is specified in adopted-info
#version: '0.2.0' # just for humans, typically '1.2+git' or '1.3.2'
#version-script: git describe --exact-match --tags 2>/dev/null || echo "develop"

grade: devel # must be 'stable' to release into candidate/stable channels
adopt-info: contour
base: core18 # the base snap is the execution environment for this snap
confinement: classic # devmode, classic, strict

apps:
  contour:
    command: bin/desktop-launch contour
    desktop: usr/share/applications/contour.desktop
    common-id: org.christianparpart.contour
    environment:
      QT_QPA_PLATFORMTHEME: "KDE"
      QT_DEBUG_PLUGINS: "1"
    plugs:
      - desktop
      - home
      - opengl
      - unity7
      - wayland
      - x11
    # extensions:
    #   - kde-neon

parts:
  contour:
    after: [qt5]
    source: .
    source-type: git
    plugin: cmake
    parse-info:
      - usr/share/appdata/contour.appdata.xml
    build-packages:
      - build-essential
      - extra-cmake-modules
      - libboost-all-dev
      - libc6-dev
      - libfontconfig1-dev
      - libfreetype6-dev
      - libharfbuzz-dev
      - libkf5windowsystem-dev
      - libqt5gui5
      - libqt5opengl5-dev
      - ncurses-bin
      - pkg-config
      - qtbase5-dev
    stage-packages:
      - libfontconfig1
      - libfreetype6
      - libglu1-mesa
      - libharfbuzz0b
      - libkf5windowsystem5
      - libqt5core5a
      - libqt5gui5
      - libqt5network5
      - busybox
    #cmake-parameters:
    configflags:
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DCMAKE_CXX_FLAGS=\"-fdiagnostics-color=always\""
      - "-DCMAKE_INSTALL_PREFIX=/"
      - "-DCONTOUR_BLUR_PLATFORM_KWIN=ON"
      - "-DCONTOUR_EXAMPLES=OFF"
      - "-DCRISPY_TESTING=OFF"
      - "-DFETCHCONTENT_QUIET=OFF"
      - "-DFETCHCONTENT_UPDATES_DISCONNECTED=ON"
      - "-DLIBTERMINAL_TESTING=OFF"
      - "-DLIBUNICODE_TESTING=OFF"

  qt5:
      source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
      source-subdir: qt
      plugin: make
      make-parameters: ["FLAVOR=qt5"]
      build-packages:
        - build-essential
        - qtbase5-dev
        - dpkg-dev
      stage-packages:
        - libxkbcommon0
        - ttf-ubuntu-font-family
        - dmz-cursor-theme
        - light-themes
        - adwaita-icon-theme
        - gnome-themes-standard
        - shared-mime-info
        - libqt5gui5
        - libgdk-pixbuf2.0-0
        - libqt5svg5 # for loading icon themes which are svg
        - try: [appmenu-qt5] # not available on core18
        - locales-all
        - libgtk2.0-0

  # Workaround for cmake-gui crash on startup with intel driver
  mesa:
    after: [qt5]
    plugin: nil
    stage-packages:
      - libgl1-mesa-dri
    # build-attributes:
    #   - no-patchelf # Otherwise snapcraft may strip the build ID and cause the driver to crash
    prime:
      - -lib/udev
      - -usr/doc
      - -usr/doc-base
      - -usr/share/applications

  # qt5-gtk-platform:
  #   plugin: nil
  #   stage-packages:
  #     - qt5-gtk-platformtheme

# plugs:
#   # Support for common GTK themes
#   # https://forum.snapcraft.io/t/how-to-use-the-system-gtk-theme-via-the-gtk-common-themes-snap/6235
#   gsettings:
#   gtk-3-themes:
#     interface: content
#     target: $SNAP/data-dir/themes
#     default-provider: gtk-common-themes
#   icon-themes:
#     interface: content
#     target: $SNAP/data-dir/icons
#     default-provider: gtk-common-themes
#   sound-themes:
#     interface: content
#     target: $SNAP/data-dir/sounds
#     default-provider: gtk-common-themes
